# Generated by Django 5.2.4 on 2025-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_marker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marker',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='marker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='title',
            field=models.CharField(default='Location Point', max_length=200),
        ),
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
