# Generated by Django 5.2.4 on 2025-09-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_marker_options_marker_description_marker_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
