# Generated by Django 5.2.4 on 2026-01-08 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_proximitynotification_userprofile_friendship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proximityalert',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('requester', 'addressee'), name='unique_friend_request'),
        ),
        migrations.AddConstraint(
            model_name='proximityalert',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_prox_alert'),
        ),
    ]
